### ISSUE TITLE
Send ArrayBuffer Stream

### ISSUE THREAD

**Issue by vin-ni** [laggingreflex/simple-socket-stream#1]
Hi, I'm trying to send an arrayBuffer from my client to server for further use with the google speech api (pipe that binaryStream to google). I got it to work with the binaryJs library, but unfortunately need to keep it to socket.io only. I've added the socket.io-stream library as well but couldn't make it work except the blob stream example for a text file.

I don't know how to generate a correct stream, because I'm not sending a file with a certain filesize but a stream for an unknown amount of time. Is there a way to handle that with your library? I've been trying it for days and just can't get it to work...

The function on the clientside that would send the binaryData looks like this:

    function recorderProcess(e) {
        var left = e.inputBuffer.getChannelData(0);
        var left16 = convertFloat32ToInt16(left);
        console.log(left16);

        // socket.emit('bianryData', left16);
    }

Obviously the standard emit won't work, because I need to to a 

    stream.pipe(recognizeStream);

on the server side. The stream would be the binaryData stream that I get from the client.

Thank you :)

**Comment by laggingreflex** [comment]
I don't quite understand your problem I'm afraid. 

This library is just a wrapper to simplify socket.io-stream's API. 

If you're simply having trouble understanding where to put `stream.pipe(recognizeStream)` it would be within the `send` and `receive` callbacks. 

Let me know if that solves it

**Comment by vin-ni** [comment]
stupid mistake of mine. `recognizeStream.write(data);` works like a charm
